apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: boot-kube-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: boot-kube-basic
      tier: app
  template:
    metadata:
      labels:
        app: boot-kube-basic
        tier: app
    spec:
      containers:
        - name: boot-kube-container
          image: kubevega2k/boot-kube:0.2